### ISSUE TITLE
API docs showing default domain name

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/objects-api#204] opened 2021-06-11 15:20 UTC
In the Utrechtproeftuin Objects API, the API docs use `example.com` as the domain name instead of the actual domain name:
![Screenshot from 2021-06-11 17-16-19](https://user-images.githubusercontent.com/19154114/121709842-42a8ba00-cad9-11eb-92f4-3cb392f0fa56.png)

**Comment by annashamray** [comment] 2021-07-21 13:25
@SilviaAmAm 
I can't see it in the Utrechtproeftuin anymore. 
I'll close the issue since it can't be reproduced

**Closed by annashamray** 2021-07-21 13:25 UTC
