### ISSUE TITLE
Token auth doesn't load in propperly in admin/token/permission/{id}/change/

### ISSUE THREAD

**Issue by bart-maykin** [maykinmedia/objects-api#404] opened 2024-05-14 07:28 UTC
![Screenshot from 2024-05-14 09-25-08](https://github.com/maykinmedia/objects-api/assets/101265650/89a977fe-babe-474e-a880-2d942a0ccaa9)

When opening the permission detail page the token auth field doesn't select the correct object but instead displays that nothing is selected.

**Comment by joeribekker** [comment] 2024-06-04 10:15
duplicate of #406

**Closed by joeribekker** 2024-06-04 10:15 UTC
Labels: bug
